### PR TITLE
colour handling added

### PR DESCRIPTION
**Pull request by matteo-naccarato**
Hi! My name is Matteo and I'm quite new in OSS... 
I found this issue looking for "good first issue" tag and I tried to implement it... I'll wait for your feedback :)

### CODE REVIEW

**Comment by Eczbek** [comment]
This is a reasonable approach!

**Comment by Ttibsi** [comment]
I quite like this approach -- Can we also add an easy way to get some basic/common colours? Potentially overload the function with another of the same name that takes in an enum value?

**Comment by matteo-naccarato** [comment]
Hi! I overloaded the function using an enum value

**Comment by Ttibsi** [comment]
Thank you for this PR. On reflection, I think the example code from @Eczbek linked on #11 [here](https://github.com/Ttibsi/rawterm/issues/11#issuecomment-1760534809) would be better suited for this project. I'm going to close this PR, but you're welcome to take the code from there and add it instead in another PR. Otherwise, I'll go ahead and assign it to Eczbek instead

**Comment by matteo-naccarato** [comment]
Yeah I agree with you, I'll take the code from @Eczbek and add it in another PR. Thanks!

**Pull request closed without merging**
